#!/bin/bash
output=../cbits/rounded-common.inl
mustache=$(which mustache mustache-2.6)
cat <<EOF > $output
/* This file was generated by etc/gen-rounded-common.sh. */
EOF
$mustache c-double.yaml rounded-common.mustache >> $output
$mustache c-float.yaml rounded-common.mustache >> $output
