#!/bin/bash
output=../cbits/rounded-common.inl
mustache=$(which mustache mustache-2.6)
cat <<EOF > $output
/* This file was generated by etc/gen-rounded-common.sh. */
EOF
cat <<EOF | $mustache - rounded-common.mustache >> $output
---
TYPE: double
NAME: double
sqrt: sqrt
fma: fma
fmax: fmax
fmin: fmin
FP_FAST_FMA: FP_FAST_FMA
each_rounding_mode:
  - MODE_PARAM: "HsInt mode, "
    MODE_ARG: "hs_rounding_mode_to_native(mode)"
  - MODE_PARAM: ""
    MODE_ARG: ROUND_UPWARD
    MODE_SUFFIX: "_up"
  - MODE_PARAM: ""
    MODE_ARG: ROUND_DOWNWARD
    MODE_SUFFIX: "_down"
  - MODE_PARAM: ""
    MODE_ARG: ROUND_TOWARDZERO
    MODE_SUFFIX: "_zero"
---
EOF
cat <<EOF | $mustache - rounded-common.mustache >> $output
---
TYPE: float
NAME: float
sqrt: sqrtf
fma: fmaf
fmax: fmaxf
fmin: fminf
FP_FAST_FMA: FP_FAST_FMAF
each_rounding_mode:
  - MODE_PARAM: "HsInt mode, "
    MODE_ARG: "hs_rounding_mode_to_native(mode)"
  - MODE_PARAM: ""
    MODE_ARG: ROUND_UPWARD
    MODE_SUFFIX: "_up"
  - MODE_PARAM: ""
    MODE_ARG: ROUND_DOWNWARD
    MODE_SUFFIX: "_down"
  - MODE_PARAM: ""
    MODE_ARG: ROUND_TOWARDZERO
    MODE_SUFFIX: "_zero"
---
EOF
