#!/bin/bash
output=../cbits/rounded-avx512.inl
mustache=$(which mustache mustache-2.6)
cat <<EOF > $output
/* This file was generated by etc/gen-rounded-avx512.sh. */
EOF
$mustache c-double.yaml rounded-avx512.mustache >> $output
$mustache c-float.yaml rounded-avx512.mustache >> $output
