-- This file was generated by etc/gen-ffi-wrapper.sh
-- DO NOT EDIT this file directly!
{-# LANGUAGE MagicHash #-}
{-# LANGUAGE UnliftedFFITypes #-}
module FFIWrapper.Double
  ( roundedAdd
  , roundedSub
  , roundedMul
  , roundedDiv
  , roundedSqrt
  , roundedFMA
  , roundedFMAIfFast
  , roundedFromInt64
  , roundedFromWord64
  , roundedSumPtr
  , roundedSumByteArray
  , intervalMul_down
  , intervalMul_up
  , intervalDiv_down
  , intervalDiv_up
  ) where
import Data.Int (Int64)
import Data.Word (Word64)
import Foreign.Ptr (Ptr)
import GHC.Exts (ByteArray#)
import Numeric.Rounded.Hardware.Internal.Rounding (RoundingMode(..))

foreign import ccall unsafe "rounded_hw_add_double"
  c_rounded_add :: Int -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_add_double_up"
  c_rounded_add_up :: Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_add_double_down"
  c_rounded_add_down :: Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_add_double_zero"
  c_rounded_add_zero :: Double -> Double -> Double

roundedAdd :: RoundingMode -> Double -> Double -> Double
roundedAdd rn = c_rounded_add (fromEnum rn)
{-# INLINE [1] roundedAdd #-}
{-# RULES
"roundedAdd/TowardNegInf" [~1] roundedAdd TowardNegInf = c_rounded_add_down
"roundedAdd/TowardInf" [~1] roundedAdd TowardInf = c_rounded_add_up
"roundedAdd/TowardZero" [~1] roundedAdd TowardZero = c_rounded_add_zero
  #-}

foreign import ccall unsafe "rounded_hw_sub_double"
  c_rounded_sub :: Int -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_sub_double_up"
  c_rounded_sub_up :: Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_sub_double_down"
  c_rounded_sub_down :: Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_sub_double_zero"
  c_rounded_sub_zero :: Double -> Double -> Double

roundedSub :: RoundingMode -> Double -> Double -> Double
roundedSub rn = c_rounded_sub (fromEnum rn)
{-# INLINE [1] roundedSub #-}
{-# RULES
"roundedSub/TowardNegInf" [~1] roundedSub TowardNegInf = c_rounded_sub_down
"roundedSub/TowardInf" [~1] roundedSub TowardInf = c_rounded_sub_up
"roundedSub/TowardZero" [~1] roundedSub TowardZero = c_rounded_sub_zero
  #-}

foreign import ccall unsafe "rounded_hw_mul_double"
  c_rounded_mul :: Int -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_mul_double_up"
  c_rounded_mul_up :: Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_mul_double_down"
  c_rounded_mul_down :: Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_mul_double_zero"
  c_rounded_mul_zero :: Double -> Double -> Double

roundedMul :: RoundingMode -> Double -> Double -> Double
roundedMul rn = c_rounded_mul (fromEnum rn)
{-# INLINE [1] roundedMul #-}
{-# RULES
"roundedMul/TowardNegInf" [~1] roundedMul TowardNegInf = c_rounded_mul_down
"roundedMul/TowardInf" [~1] roundedMul TowardInf = c_rounded_mul_up
"roundedMul/TowardZero" [~1] roundedMul TowardZero = c_rounded_mul_zero
  #-}

foreign import ccall unsafe "rounded_hw_div_double"
  c_rounded_div :: Int -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_div_double_up"
  c_rounded_div_up :: Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_div_double_down"
  c_rounded_div_down :: Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_div_double_zero"
  c_rounded_div_zero :: Double -> Double -> Double

roundedDiv :: RoundingMode -> Double -> Double -> Double
roundedDiv rn = c_rounded_div (fromEnum rn)
{-# INLINE [1] roundedDiv #-}
{-# RULES
"roundedDiv/TowardNegInf" [~1] roundedDiv TowardNegInf = c_rounded_div_down
"roundedDiv/TowardInf" [~1] roundedDiv TowardInf = c_rounded_div_up
"roundedDiv/TowardZero" [~1] roundedDiv TowardZero = c_rounded_div_zero
  #-}

foreign import ccall unsafe "rounded_hw_sqrt_double"
  c_rounded_sqrt :: Int -> Double -> Double
foreign import ccall unsafe "rounded_hw_sqrt_double_up"
  c_rounded_sqrt_up :: Double -> Double
foreign import ccall unsafe "rounded_hw_sqrt_double_down"
  c_rounded_sqrt_down :: Double -> Double
foreign import ccall unsafe "rounded_hw_sqrt_double_zero"
  c_rounded_sqrt_zero :: Double -> Double

roundedSqrt :: RoundingMode -> Double -> Double
roundedSqrt rn = c_rounded_sqrt (fromEnum rn)
{-# INLINE [1] roundedSqrt #-}
{-# RULES
"roundedSqrt/TowardNegInf" [~1] roundedSqrt TowardNegInf = c_rounded_sqrt_down
"roundedSqrt/TowardInf" [~1] roundedSqrt TowardInf = c_rounded_sqrt_up
"roundedSqrt/TowardZero" [~1] roundedSqrt TowardZero = c_rounded_sqrt_zero
  #-}

foreign import ccall unsafe "rounded_hw_fma_double"
  c_rounded_fma :: Int -> Double -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_fma_double_up"
  c_rounded_fma_up :: Double -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_fma_double_down"
  c_rounded_fma_down :: Double -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_fma_double_zero"
  c_rounded_fma_zero :: Double -> Double -> Double -> Double

roundedFMA :: RoundingMode -> Double -> Double -> Double -> Double
roundedFMA rn = c_rounded_fma (fromEnum rn)
{-# INLINE [1] roundedFMA #-}
{-# RULES
"roundedFMA/TowardNegInf" [~1] roundedFMA TowardNegInf = c_rounded_fma_down
"roundedFMA/TowardInf" [~1] roundedFMA TowardInf = c_rounded_fma_up
"roundedFMA/TowardZero" [~1] roundedFMA TowardZero = c_rounded_fma_zero
  #-}

foreign import ccall unsafe "rounded_hw_fma_if_fast_double"
  c_rounded_fma_if_fast :: Int -> Double -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_fma_if_fast_double_up"
  c_rounded_fma_if_fast_up :: Double -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_fma_if_fast_double_down"
  c_rounded_fma_if_fast_down :: Double -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_fma_if_fast_double_zero"
  c_rounded_fma_if_fast_zero :: Double -> Double -> Double -> Double

roundedFMAIfFast :: RoundingMode -> Double -> Double -> Double -> Double
roundedFMAIfFast rn = c_rounded_fma_if_fast (fromEnum rn)
{-# INLINE [1] roundedFMAIfFast #-}
{-# RULES
"roundedFMAIfFast/TowardNegInf" [~1] roundedFMAIfFast TowardNegInf = c_rounded_fma_if_fast_down
"roundedFMAIfFast/TowardInf" [~1] roundedFMAIfFast TowardInf = c_rounded_fma_if_fast_up
"roundedFMAIfFast/TowardZero" [~1] roundedFMAIfFast TowardZero = c_rounded_fma_if_fast_zero
  #-}

foreign import ccall unsafe "rounded_hw_int64_to_double"
  c_rounded_from_int64 :: Int -> Int64 -> Double
foreign import ccall unsafe "rounded_hw_int64_to_double_up"
  c_rounded_from_int64_up :: Int64 -> Double
foreign import ccall unsafe "rounded_hw_int64_to_double_down"
  c_rounded_from_int64_down :: Int64 -> Double
foreign import ccall unsafe "rounded_hw_int64_to_double_zero"
  c_rounded_from_int64_zero :: Int64 -> Double

roundedFromInt64 :: RoundingMode -> Int64 -> Double
roundedFromInt64 rn = c_rounded_from_int64 (fromEnum rn)
{-# INLINE [1] roundedFromInt64 #-}
{-# RULES
"roundedFromInt64/TowardNegInf" [~1] roundedFromInt64 TowardNegInf = c_rounded_from_int64_down
"roundedFromInt64/TowardInf" [~1] roundedFromInt64 TowardInf = c_rounded_from_int64_up
"roundedFromInt64/TowardZero" [~1] roundedFromInt64 TowardZero = c_rounded_from_int64_zero
  #-}

foreign import ccall unsafe "rounded_hw_word64_to_double"
  c_rounded_from_word64 :: Int -> Word64 -> Double
foreign import ccall unsafe "rounded_hw_word64_to_double_up"
  c_rounded_from_word64_up :: Word64 -> Double
foreign import ccall unsafe "rounded_hw_word64_to_double_down"
  c_rounded_from_word64_down :: Word64 -> Double
foreign import ccall unsafe "rounded_hw_word64_to_double_zero"
  c_rounded_from_word64_zero :: Word64 -> Double

roundedFromWord64 :: RoundingMode -> Word64 -> Double
roundedFromWord64 rn = c_rounded_from_word64 (fromEnum rn)
{-# INLINE [1] roundedFromWord64 #-}
{-# RULES
"roundedFromWord64/TowardNegInf" [~1] roundedFromWord64 TowardNegInf = c_rounded_from_word64_down
"roundedFromWord64/TowardInf" [~1] roundedFromWord64 TowardInf = c_rounded_from_word64_up
"roundedFromWord64/TowardZero" [~1] roundedFromWord64 TowardZero = c_rounded_from_word64_zero
  #-}

foreign import ccall unsafe "rounded_hw_sum_double"
  c_rounded_sum_ptr :: Int -> Int -> Int -> Ptr Double -> IO Double
foreign import ccall unsafe "rounded_hw_sum_double_up"
  c_rounded_sum_ptr_up :: Int -> Int -> Ptr Double -> IO Double
foreign import ccall unsafe "rounded_hw_sum_double_down"
  c_rounded_sum_ptr_down :: Int -> Int -> Ptr Double -> IO Double
foreign import ccall unsafe "rounded_hw_sum_double_zero"
  c_rounded_sum_ptr_zero :: Int -> Int -> Ptr Double -> IO Double

roundedSumPtr :: RoundingMode -> Int -> Int -> Ptr Double -> IO Double
roundedSumPtr rn = c_rounded_sum_ptr (fromEnum rn)
{-# INLINE [1] roundedSumPtr #-}
{-# RULES
"roundedSumPtr/TowardNegInf" [~1] roundedSumPtr TowardNegInf = c_rounded_sum_ptr_down
"roundedSumPtr/TowardInf" [~1] roundedSumPtr TowardInf = c_rounded_sum_ptr_up
"roundedSumPtr/TowardZero" [~1] roundedSumPtr TowardZero = c_rounded_sum_ptr_zero
  #-}

foreign import ccall unsafe "rounded_hw_sum_double"
  c_rounded_sum_bytearr :: Int -> Int -> Int -> ByteArray# -> Double
foreign import ccall unsafe "rounded_hw_sum_double_up"
  c_rounded_sum_bytearr_up :: Int -> Int -> ByteArray# -> Double
foreign import ccall unsafe "rounded_hw_sum_double_down"
  c_rounded_sum_bytearr_down :: Int -> Int -> ByteArray# -> Double
foreign import ccall unsafe "rounded_hw_sum_double_zero"
  c_rounded_sum_bytearr_zero :: Int -> Int -> ByteArray# -> Double

roundedSumByteArray :: RoundingMode -> Int -> Int -> ByteArray# -> Double
roundedSumByteArray rn = c_rounded_sum_bytearr (fromEnum rn)
{-# INLINE [1] roundedSumByteArray #-}
{-# RULES
"roundedSumByteArray/TowardNegInf" [~1] roundedSumByteArray TowardNegInf = c_rounded_sum_bytearr_down
"roundedSumByteArray/TowardInf" [~1] roundedSumByteArray TowardInf = c_rounded_sum_bytearr_up
"roundedSumByteArray/TowardZero" [~1] roundedSumByteArray TowardZero = c_rounded_sum_bytearr_zero
  #-}

foreign import ccall unsafe "rounded_hw_interval_mul_double_down"
  intervalMul_down :: Double -> Double -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_interval_mul_double_up"
  intervalMul_up :: Double -> Double -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_interval_div_double_down"
  intervalDiv_down :: Double -> Double -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_interval_div_double_up"
  intervalDiv_up :: Double -> Double -> Double -> Double -> Double
