-- This file was generated by etc/GenFFIWrapper.hs
-- DO NOT EDIT this file directly!
{-# LANGUAGE MagicHash #-}
{-# LANGUAGE UnliftedFFITypes #-}
module FFIWrapper.Float where
import Data.Int
import Data.Word
import GHC.Exts
import Numeric.Rounded.Hardware.Base.Rounding
import FFIImports

roundedAdd :: RoundingMode -> Float -> Float -> Float
roundedAdd rn = c_rounded_add_float (fromEnum rn)
{-# INLINE [1] roundedAdd #-}
{-# RULES
"roundedAdd/TowardNegInf" [~1] roundedAdd TowardNegInf = c_rounded_add_float_down
"roundedAdd/TowardInf" [~1] roundedAdd TowardInf = c_rounded_add_float_up
"roundedAdd/TowardZero" [~1] roundedAdd TowardZero = c_rounded_add_float_zero
  #-}

roundedSub :: RoundingMode -> Float -> Float -> Float
roundedSub rn = c_rounded_sub_float (fromEnum rn)
{-# INLINE [1] roundedSub #-}
{-# RULES
"roundedSub/TowardNegInf" [~1] roundedSub TowardNegInf = c_rounded_sub_float_down
"roundedSub/TowardInf" [~1] roundedSub TowardInf = c_rounded_sub_float_up
"roundedSub/TowardZero" [~1] roundedSub TowardZero = c_rounded_sub_float_zero
  #-}

roundedMul :: RoundingMode -> Float -> Float -> Float
roundedMul rn = c_rounded_mul_float (fromEnum rn)
{-# INLINE [1] roundedMul #-}
{-# RULES
"roundedMul/TowardNegInf" [~1] roundedMul TowardNegInf = c_rounded_mul_float_down
"roundedMul/TowardInf" [~1] roundedMul TowardInf = c_rounded_mul_float_up
"roundedMul/TowardZero" [~1] roundedMul TowardZero = c_rounded_mul_float_zero
  #-}

roundedDiv :: RoundingMode -> Float -> Float -> Float
roundedDiv rn = c_rounded_div_float (fromEnum rn)
{-# INLINE [1] roundedDiv #-}
{-# RULES
"roundedDiv/TowardNegInf" [~1] roundedDiv TowardNegInf = c_rounded_div_float_down
"roundedDiv/TowardInf" [~1] roundedDiv TowardInf = c_rounded_div_float_up
"roundedDiv/TowardZero" [~1] roundedDiv TowardZero = c_rounded_div_float_zero
  #-}

roundedSqrt :: RoundingMode -> Float -> Float
roundedSqrt rn = c_rounded_sqrt_float (fromEnum rn)
{-# INLINE [1] roundedSqrt #-}
{-# RULES
"roundedSqrt/TowardNegInf" [~1] roundedSqrt TowardNegInf = c_rounded_sqrt_float_down
"roundedSqrt/TowardInf" [~1] roundedSqrt TowardInf = c_rounded_sqrt_float_up
"roundedSqrt/TowardZero" [~1] roundedSqrt TowardZero = c_rounded_sqrt_float_zero
  #-}

roundedFMA :: RoundingMode -> Float -> Float -> Float -> Float
roundedFMA rn = c_rounded_fma_float (fromEnum rn)
{-# INLINE [1] roundedFMA #-}
{-# RULES
"roundedFMA/TowardNegInf" [~1] roundedFMA TowardNegInf = c_rounded_fma_float_down
"roundedFMA/TowardInf" [~1] roundedFMA TowardInf = c_rounded_fma_float_up
"roundedFMA/TowardZero" [~1] roundedFMA TowardZero = c_rounded_fma_float_zero
  #-}

roundedFromInt64 :: RoundingMode -> Int64 -> Float
roundedFromInt64 rn = c_rounded_int64_to_float (fromEnum rn)
{-# INLINE [1] roundedFromInt64 #-}
{-# RULES
"roundedFromInt64/TowardNegInf" [~1] roundedFromInt64 TowardNegInf = c_rounded_int64_to_float_down
"roundedFromInt64/TowardInf" [~1] roundedFromInt64 TowardInf = c_rounded_int64_to_float_up
"roundedFromInt64/TowardZero" [~1] roundedFromInt64 TowardZero = c_rounded_int64_to_float_zero
  #-}

roundedFromWord64 :: RoundingMode -> Word64 -> Float
roundedFromWord64 rn = c_rounded_word64_to_float (fromEnum rn)
{-# INLINE [1] roundedFromWord64 #-}
{-# RULES
"roundedFromWord64/TowardNegInf" [~1] roundedFromWord64 TowardNegInf = c_rounded_word64_to_float_down
"roundedFromWord64/TowardInf" [~1] roundedFromWord64 TowardInf = c_rounded_word64_to_float_up
"roundedFromWord64/TowardZero" [~1] roundedFromWord64 TowardZero = c_rounded_word64_to_float_zero
  #-}

roundedSumPtr :: RoundingMode -> Int -> Int -> Ptr Float -> IO Float
roundedSumPtr rn = c_rounded_sum_ptr_float (fromEnum rn)
{-# INLINE [1] roundedSumPtr #-}
{-# RULES
"roundedSumPtr/TowardNegInf" [~1] roundedSumPtr TowardNegInf = c_rounded_sum_ptr_float_down
"roundedSumPtr/TowardInf" [~1] roundedSumPtr TowardInf = c_rounded_sum_ptr_float_up
"roundedSumPtr/TowardZero" [~1] roundedSumPtr TowardZero = c_rounded_sum_ptr_float_zero
  #-}

roundedSumByteArray :: RoundingMode -> Int -> Int -> ByteArray# -> Float
roundedSumByteArray rn = c_rounded_sum_bytearr_float (fromEnum rn)
{-# INLINE [1] roundedSumByteArray #-}
{-# RULES
"roundedSumByteArray/TowardNegInf" [~1] roundedSumByteArray TowardNegInf = c_rounded_sum_bytearr_float_down
"roundedSumByteArray/TowardInf" [~1] roundedSumByteArray TowardInf = c_rounded_sum_bytearr_float_up
"roundedSumByteArray/TowardZero" [~1] roundedSumByteArray TowardZero = c_rounded_sum_bytearr_float_zero
  #-}
