-- This file was generated by etc/GenFFIImports.hs
-- DO NOT EDIT this file directly!
{-# LANGUAGE MagicHash #-}
{-# LANGUAGE UnliftedFFITypes #-}
module FFIImports where
import Data.Int
import Data.Word
import GHC.Exts

foreign import ccall unsafe "rounded_hw_add_float"
  c_rounded_add_float :: Int -> Float -> Float -> Float
foreign import ccall unsafe "rounded_hw_add_float_up"
  c_rounded_add_float_up :: Float -> Float -> Float
foreign import ccall unsafe "rounded_hw_add_float_down"
  c_rounded_add_float_down :: Float -> Float -> Float
foreign import ccall unsafe "rounded_hw_add_float_zero"
  c_rounded_add_float_zero :: Float -> Float -> Float

foreign import ccall unsafe "rounded_hw_sub_float"
  c_rounded_sub_float :: Int -> Float -> Float -> Float
foreign import ccall unsafe "rounded_hw_sub_float_up"
  c_rounded_sub_float_up :: Float -> Float -> Float
foreign import ccall unsafe "rounded_hw_sub_float_down"
  c_rounded_sub_float_down :: Float -> Float -> Float
foreign import ccall unsafe "rounded_hw_sub_float_zero"
  c_rounded_sub_float_zero :: Float -> Float -> Float

foreign import ccall unsafe "rounded_hw_mul_float"
  c_rounded_mul_float :: Int -> Float -> Float -> Float
foreign import ccall unsafe "rounded_hw_mul_float_up"
  c_rounded_mul_float_up :: Float -> Float -> Float
foreign import ccall unsafe "rounded_hw_mul_float_down"
  c_rounded_mul_float_down :: Float -> Float -> Float
foreign import ccall unsafe "rounded_hw_mul_float_zero"
  c_rounded_mul_float_zero :: Float -> Float -> Float

foreign import ccall unsafe "rounded_hw_div_float"
  c_rounded_div_float :: Int -> Float -> Float -> Float
foreign import ccall unsafe "rounded_hw_div_float_up"
  c_rounded_div_float_up :: Float -> Float -> Float
foreign import ccall unsafe "rounded_hw_div_float_down"
  c_rounded_div_float_down :: Float -> Float -> Float
foreign import ccall unsafe "rounded_hw_div_float_zero"
  c_rounded_div_float_zero :: Float -> Float -> Float

foreign import ccall unsafe "rounded_hw_sqrt_float"
  c_rounded_sqrt_float :: Int -> Float -> Float
foreign import ccall unsafe "rounded_hw_sqrt_float_up"
  c_rounded_sqrt_float_up :: Float -> Float
foreign import ccall unsafe "rounded_hw_sqrt_float_down"
  c_rounded_sqrt_float_down :: Float -> Float
foreign import ccall unsafe "rounded_hw_sqrt_float_zero"
  c_rounded_sqrt_float_zero :: Float -> Float

foreign import ccall unsafe "rounded_hw_fma_float"
  c_rounded_fma_float :: Int -> Float -> Float -> Float -> Float
foreign import ccall unsafe "rounded_hw_fma_float_up"
  c_rounded_fma_float_up :: Float -> Float -> Float -> Float
foreign import ccall unsafe "rounded_hw_fma_float_down"
  c_rounded_fma_float_down :: Float -> Float -> Float -> Float
foreign import ccall unsafe "rounded_hw_fma_float_zero"
  c_rounded_fma_float_zero :: Float -> Float -> Float -> Float

foreign import ccall unsafe "rounded_hw_fma_if_fast_float"
  c_rounded_fma_if_fast_float :: Int -> Float -> Float -> Float -> Float
foreign import ccall unsafe "rounded_hw_fma_if_fast_float_up"
  c_rounded_fma_if_fast_float_up :: Float -> Float -> Float -> Float
foreign import ccall unsafe "rounded_hw_fma_if_fast_float_down"
  c_rounded_fma_if_fast_float_down :: Float -> Float -> Float -> Float
foreign import ccall unsafe "rounded_hw_fma_if_fast_float_zero"
  c_rounded_fma_if_fast_float_zero :: Float -> Float -> Float -> Float

foreign import ccall unsafe "rounded_hw_int64_to_float"
  c_rounded_int64_to_float :: Int -> Int64 -> Float
foreign import ccall unsafe "rounded_hw_int64_to_float_up"
  c_rounded_int64_to_float_up :: Int64 -> Float
foreign import ccall unsafe "rounded_hw_int64_to_float_down"
  c_rounded_int64_to_float_down :: Int64 -> Float
foreign import ccall unsafe "rounded_hw_int64_to_float_zero"
  c_rounded_int64_to_float_zero :: Int64 -> Float

foreign import ccall unsafe "rounded_hw_word64_to_float"
  c_rounded_word64_to_float :: Int -> Word64 -> Float
foreign import ccall unsafe "rounded_hw_word64_to_float_up"
  c_rounded_word64_to_float_up :: Word64 -> Float
foreign import ccall unsafe "rounded_hw_word64_to_float_down"
  c_rounded_word64_to_float_down :: Word64 -> Float
foreign import ccall unsafe "rounded_hw_word64_to_float_zero"
  c_rounded_word64_to_float_zero :: Word64 -> Float

foreign import ccall unsafe "rounded_hw_sum_float"
  c_rounded_sum_ptr_float :: Int -> Int -> Int -> Ptr Float -> IO Float
foreign import ccall unsafe "rounded_hw_sum_float_up"
  c_rounded_sum_ptr_float_up :: Int -> Int -> Ptr Float -> IO Float
foreign import ccall unsafe "rounded_hw_sum_float_down"
  c_rounded_sum_ptr_float_down :: Int -> Int -> Ptr Float -> IO Float
foreign import ccall unsafe "rounded_hw_sum_float_zero"
  c_rounded_sum_ptr_float_zero :: Int -> Int -> Ptr Float -> IO Float

foreign import ccall unsafe "rounded_hw_sum_float"
  c_rounded_sum_bytearr_float :: Int -> Int -> Int -> ByteArray# -> Float
foreign import ccall unsafe "rounded_hw_sum_float_up"
  c_rounded_sum_bytearr_float_up :: Int -> Int -> ByteArray# -> Float
foreign import ccall unsafe "rounded_hw_sum_float_down"
  c_rounded_sum_bytearr_float_down :: Int -> Int -> ByteArray# -> Float
foreign import ccall unsafe "rounded_hw_sum_float_zero"
  c_rounded_sum_bytearr_float_zero :: Int -> Int -> ByteArray# -> Float

foreign import ccall unsafe "rounded_hw_interval_mul_float_up"
  c_interval_mul_float_up :: Float -> Float -> Float -> Float -> Float
foreign import ccall unsafe "rounded_hw_interval_mul_float_down"
  c_interval_mul_float_down :: Float -> Float -> Float -> Float -> Float

foreign import ccall unsafe "rounded_hw_interval_div_float_up"
  c_interval_div_float_up :: Float -> Float -> Float -> Float -> Float
foreign import ccall unsafe "rounded_hw_interval_div_float_down"
  c_interval_div_float_down :: Float -> Float -> Float -> Float -> Float

foreign import ccall unsafe "rounded_hw_add_double"
  c_rounded_add_double :: Int -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_add_double_up"
  c_rounded_add_double_up :: Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_add_double_down"
  c_rounded_add_double_down :: Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_add_double_zero"
  c_rounded_add_double_zero :: Double -> Double -> Double

foreign import ccall unsafe "rounded_hw_sub_double"
  c_rounded_sub_double :: Int -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_sub_double_up"
  c_rounded_sub_double_up :: Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_sub_double_down"
  c_rounded_sub_double_down :: Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_sub_double_zero"
  c_rounded_sub_double_zero :: Double -> Double -> Double

foreign import ccall unsafe "rounded_hw_mul_double"
  c_rounded_mul_double :: Int -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_mul_double_up"
  c_rounded_mul_double_up :: Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_mul_double_down"
  c_rounded_mul_double_down :: Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_mul_double_zero"
  c_rounded_mul_double_zero :: Double -> Double -> Double

foreign import ccall unsafe "rounded_hw_div_double"
  c_rounded_div_double :: Int -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_div_double_up"
  c_rounded_div_double_up :: Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_div_double_down"
  c_rounded_div_double_down :: Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_div_double_zero"
  c_rounded_div_double_zero :: Double -> Double -> Double

foreign import ccall unsafe "rounded_hw_sqrt_double"
  c_rounded_sqrt_double :: Int -> Double -> Double
foreign import ccall unsafe "rounded_hw_sqrt_double_up"
  c_rounded_sqrt_double_up :: Double -> Double
foreign import ccall unsafe "rounded_hw_sqrt_double_down"
  c_rounded_sqrt_double_down :: Double -> Double
foreign import ccall unsafe "rounded_hw_sqrt_double_zero"
  c_rounded_sqrt_double_zero :: Double -> Double

foreign import ccall unsafe "rounded_hw_fma_double"
  c_rounded_fma_double :: Int -> Double -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_fma_double_up"
  c_rounded_fma_double_up :: Double -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_fma_double_down"
  c_rounded_fma_double_down :: Double -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_fma_double_zero"
  c_rounded_fma_double_zero :: Double -> Double -> Double -> Double

foreign import ccall unsafe "rounded_hw_fma_if_fast_double"
  c_rounded_fma_if_fast_double :: Int -> Double -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_fma_if_fast_double_up"
  c_rounded_fma_if_fast_double_up :: Double -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_fma_if_fast_double_down"
  c_rounded_fma_if_fast_double_down :: Double -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_fma_if_fast_double_zero"
  c_rounded_fma_if_fast_double_zero :: Double -> Double -> Double -> Double

foreign import ccall unsafe "rounded_hw_int64_to_double"
  c_rounded_int64_to_double :: Int -> Int64 -> Double
foreign import ccall unsafe "rounded_hw_int64_to_double_up"
  c_rounded_int64_to_double_up :: Int64 -> Double
foreign import ccall unsafe "rounded_hw_int64_to_double_down"
  c_rounded_int64_to_double_down :: Int64 -> Double
foreign import ccall unsafe "rounded_hw_int64_to_double_zero"
  c_rounded_int64_to_double_zero :: Int64 -> Double

foreign import ccall unsafe "rounded_hw_word64_to_double"
  c_rounded_word64_to_double :: Int -> Word64 -> Double
foreign import ccall unsafe "rounded_hw_word64_to_double_up"
  c_rounded_word64_to_double_up :: Word64 -> Double
foreign import ccall unsafe "rounded_hw_word64_to_double_down"
  c_rounded_word64_to_double_down :: Word64 -> Double
foreign import ccall unsafe "rounded_hw_word64_to_double_zero"
  c_rounded_word64_to_double_zero :: Word64 -> Double

foreign import ccall unsafe "rounded_hw_sum_double"
  c_rounded_sum_ptr_double :: Int -> Int -> Int -> Ptr Double -> IO Double
foreign import ccall unsafe "rounded_hw_sum_double_up"
  c_rounded_sum_ptr_double_up :: Int -> Int -> Ptr Double -> IO Double
foreign import ccall unsafe "rounded_hw_sum_double_down"
  c_rounded_sum_ptr_double_down :: Int -> Int -> Ptr Double -> IO Double
foreign import ccall unsafe "rounded_hw_sum_double_zero"
  c_rounded_sum_ptr_double_zero :: Int -> Int -> Ptr Double -> IO Double

foreign import ccall unsafe "rounded_hw_sum_double"
  c_rounded_sum_bytearr_double :: Int -> Int -> Int -> ByteArray# -> Double
foreign import ccall unsafe "rounded_hw_sum_double_up"
  c_rounded_sum_bytearr_double_up :: Int -> Int -> ByteArray# -> Double
foreign import ccall unsafe "rounded_hw_sum_double_down"
  c_rounded_sum_bytearr_double_down :: Int -> Int -> ByteArray# -> Double
foreign import ccall unsafe "rounded_hw_sum_double_zero"
  c_rounded_sum_bytearr_double_zero :: Int -> Int -> ByteArray# -> Double

foreign import ccall unsafe "rounded_hw_interval_mul_double_up"
  c_interval_mul_double_up :: Double -> Double -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_interval_mul_double_down"
  c_interval_mul_double_down :: Double -> Double -> Double -> Double -> Double

foreign import ccall unsafe "rounded_hw_interval_div_double_up"
  c_interval_div_double_up :: Double -> Double -> Double -> Double -> Double
foreign import ccall unsafe "rounded_hw_interval_div_double_down"
  c_interval_div_double_down :: Double -> Double -> Double -> Double -> Double
